---
name: Build Ubuntu packages

on:
  workflow_dispatch:
    inputs:
      slurm_version:
        description: Slurm version to build
        default: 25.05.8
        type: string
      ubuntu_version:
        description: Ubuntu version to build on
        default: ubuntu-latest
        type: string

jobs:
  build:
    runs-on: ${{ inputs.ubuntu_version }}
    name: "Build slurm deb packages"
    permissions:
      contents: write
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential fakeroot devscripts equivs wget
      - name: Download slurm release
        run: |
          SLURM_VERSION="${{ inputs.slurm_version }}"
          wget "https://github.com/SchedMD/slurm/releases/download/slurm-${SLURM_VERSION//./-}-1/slurm-${SLURM_VERSION}.tar.bz2" 
          tar -xaf slurm-${SLURM_VERSION}.tar.bz2
          cd slurm-${SLURM_VERSION}
          sudo mk-build-deps -i -t "apt-get --yes" debian/control
          debuild -b -uc -us
          cd ..
      - name: Archive packages
        id: tar
        run: |
          # Add grep on ID ? (?<=ID=)[a-z]*$
          UBUNTU_VERSION="ubuntu-$(grep -oP '(?<=VERSION_ID=\")[0-9]{2}\.[0-9]+' /etc/os-release)"
          tar -czvf "${UBUNTU_VERSION}.tar.gz" *.deb
          echo "ubuntu_version=${UBUNTU_VERSION}" >> $GITHUB_OUTPUT
      - name: Upload as artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ${{ steps.tar.outputs.ubuntu_version }}
          path: ${{ steps.tar.outputs.ubuntu_version }}.tar.gz
          retention-days: 1
      - name: Release
        uses: zckv/action-update-release@v1
        with:
          tag: slurm-${{ inputs.slurm_version }}
          files: ${{ steps.tar.outputs.ubuntu_version }}.tar.gz
